#!/bin/sh
read -r host < /proc/sys/kernel/hostname
read -r kernel < /proc/sys/kernel/osrelease
. /etc/os-release

while read -r line; do
    [ "${line#exec }" = "$line" ] || wm="${line#exec }"
done < "$HOME/.xinitrc"

c0="\033[0m"
c1="\033[37m"

printf "%b" "

    ${c1}     .-.         
    ${c1}  __/   (        ${USER}${c0}@${c1}${host}
    ${c1}, '-.____\\\\       ${c1}os      ${PRETTY_NAME}
    ${c1} u=='/  \\\\        ${c1}kernel  ${kernel}
    ${c1}    /_/  \\\\       ${c1}shell   ${SHELL##*/}
    ${c1}  .-''   |       ${c1}wm      ${wm##*/}
    ${c1} (  ____/_____   ${c0}

"
